### ISSUE TITLE
[Suggestion] Nodding off instead of Blindness

### ISSUE THREAD

**Issue by belathus** [OndraSter/BetterSleeping#15]
Someone that was testing my modpack with me suggested that instead of straight-up blindness, you randomly got afflicted with short-duration blindness as if you were nodding off. I liked the idea.

**Comment by CallMeFoxie** [comment]
Sounds possible, will see what I can do :)

**Comment by CallMeFoxie** [comment]
1.7.10 is no longer supported, if it is still relevant, please repost at https://github.com/CallMeFoxie/BetterSleeping2
