### ISSUE TITLE
Sleeping % notification is broke

### ISSUE THREAD

**Issue by Claycorp** [OndraSter/BetterSleeping#20]
I have the sleep % to skip set to 1.0 and enabled the notification.

When one person is sleeping nothing shows but if others start sleeping it just says 0.0% are sleeping regardless of people sleeping.

Console throws nothing and displays no messages.

**Comment by CallMeFoxie** [comment]
:/ This issue will be fun to debug as I do not have multiple MC accounts.
I know where it might be coming from, but for now, please, add and use Morpheus as my mod should integrate into it.

**Comment by AbrarSyed** [comment]
You can test very easily in the development environment. Start a server, and then start multiple clients with different versions. You can run the server in offline mode and connect without having a password for each client. Thats how all the rest of us mod devs do it.

You can run and debug these in your IDE with the correct run configs.. Ive done tests where ive had 3 clients connected to 1 local server. You just need different run configs for each client. You can use `--username myUsername` to set the username.

**Comment by CallMeFoxie** [comment]
@AbrarSyed clients with different versions? They cannot match the version?

**Comment by AbrarSyed** [comment]
if people are having issues with an earlier version, then yuo can just tell them they need to get the latest. FML also has stuff for checking what versions are allowed to connect: https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/Mod.java#L112-L121

bad example of it in use:  https://github.com/AbrarSyed/SecretRoomsMod-forge/blob/master/src/main/java/com/github/abrarsyed/secretroomsmod/common/SecretRooms.java#L59

**Comment by CallMeFoxie** [comment]
Oh I thought that you meant in order to debug the issue I needed different versions of the mod.

Yes, I know about acceptableRemoteVersions then.

Will see if it works, I had problems with it in the past. Thanks!

**Comment by AbrarSyed** [comment]
Oh, hah no. It would actually be hard to have 2 different versions of the mod connected in the dev env. You would be executing both clients off of the exact same code...

**Comment by CallMeFoxie** [comment]
1.7.10 is no longer supported, if it is still relevant, please repost at https://github.com/CallMeFoxie/BetterSleeping2
