### ISSUE TITLE
Sleep meter not working after first sleep

### ISSUE THREAD

**Issue by Echo343** [OndraSter/BetterSleeping#21]
Setup:
1) Multiplayer Forge server version 1.7.10-10.13.3.1391 or 1.7.10-10.13.3.1370
2) BetterSleeping version 1.7.10-0.9

Steps to Reproduce:
1) Enter new world
2) Enter creative mode and give yourself a bed and a stack of Baked Potatoes
3) Enter Survival mode
4) Sprint around until sleep meter drops at least one tick.
5) Place bed and sleep
6) After sleep, sprint around some more until sleep meter drops a tick.

Expected Result:
The sleep meter should drop some ticks after sprinting around.

Actual Result:
Sprinting around for 10 mins does not drop the sleep meter after the first sleep.  Attempting to sleep gives the message, "You are not tired."

Note:
After the first sleep, if you kill your player, respawn, and then sprint around your sleep meter will behave appropriately and drop in ticks as expected.

**Comment by CallMeFoxie** [comment]
You can "oversleep" your meter, similar to how saturation works with hunger. Try sleeping just 1 hour. Works just fine.

**Comment by Echo343** [comment]
Ah, well that makes sense now.  Thanks! =)
