### ISSUE TITLE
[Request] Witchery Integration

### ISSUE THREAD

**Issue by solomon56** [OndraSter/BetterSleeping#22]
Pretty low priority request but it would be nice if vampires and werewolves from the Witchery mod didn't have to deal with sleep related effects that normal players have to (being supernatural and all their stamina is not relevant)

Thanks!
-solomon56

**Comment by CallMeFoxie** [comment]
Eh, I would like to but Witchery does not have any API available nor it is opensource. Either I need some API to hook into (from Witchery) or have Witchery to hook into my API. Cannot do it from my side, sorry.

Feel free to reference this on Witchery's issues.

PS: If Witchery is missing something in my API, I can add it.

**Comment by solomon56** [comment]
This is more of what I had in mind for the time being if you do decide you want to implement it on your end. Witchery does not seem to have an API or even be remotely Open Source. Slightly "hacky" to get the data from NBT tags. https://github.com/OndraSter/BetterSleeping/pull/23
