### ISSUE TITLE
Caffeine + Hunger Overhaul

### ISSUE THREAD

**Issue by belathus** [OndraSter/BetterSleeping#25]
I have been trying to modify the configs to make caffeine meaningful to reducing tiredness, but I cannot seem to be able to make it so with Hunger Overhaul installed.

Looking through code, it looks like the caffeine increase is the food value multiplied by the config value (6 by default), while the tiredness decrease is based off saturation (multiplied by 200 by default). Coffee gives none of either with HO, though, I still get sick from drinking too much, so I wonder, is it ignoring the hunger changes from HO? If so, I think coffee gives 4 hunger and 0.6 saturation by default, meaning I can drink 3 before dying at 72 caffeine and only reducing my tiredness by 360 out of 18,000? I suppose this is underwhelming at default configs.

I did increase the tiredness given by food to the max value listed in the config (1000) and decreased the caffeine given by half while increasing the amount of caffeine required for getting sick to 100, yet by the time I am getting sick I am not seeing any change to the tiredness meter.

Also, which items are not food items that you can consume? I'm guessing that is for some item like a caffeine pill?

Looking here for Hunger Overhaul food values: https://github.com/progwml6/HungerOverhaul/blob/master/src/main/java/iguanaman/hungeroverhaul/module/ModuleHarvestCraft.java

**Comment by CallMeFoxie** [comment]
I have not tested the mod with some low value foods honestly, did not think of that. I can up the max values, I usually do 1000 because it is nice and round number and works in most cases.

The code checks for any used (eaten) item. If it oredicts to the config values it will do its magic. Was thinking of adding pills but I want to keep the item/block count to as least as possible. Although I might add them in the future. (Inb4 Minecraft 1.9 will have rewritten item code ><)

**Comment by CallMeFoxie** [comment]
Oops I lied there a bit.
The food is treated as:
if the item oredict is registered and listed in the config:
- if the item is a food then apply multipliers
- otherwise apply tirednessPerCaffeine and caffeinePerItem

**Comment by CallMeFoxie** [comment]
Upped the max values for the new release 0.11, hope it is enough :)

**Comment by belathus** [comment]
It looks like it will be. I spent a good deal of time Thursday playing with the values, reducing the overall tiredness by a factor of 10 while keeping the caffeine at max values, and it does make a difference when consumed. You still need a lot of it, but it does help.

I am not a modder, but I almost wouldn't mind making a tiny addon that adds caffeine pills and sleeping pills.

**Comment by CallMeFoxie** [comment]
Might add it over the weekend or early next week before I leave for Minecon then :)

**Comment by CallMeFoxie** [comment]
Actually added in the latest version, forgot to post ^^
