### ISSUE TITLE
Config lore

### ISSUE THREAD

**Issue by K4N0** [OndraSter/BetterSleeping#26]
I wanted players to have a bigger sleeping bar. so that players don't have to go to sleep so often.
I wanted when players sleep to get a full bar within 8 sec. i don't like sleeping for 5min at a time.
My server has 30min days and 30min nights real time. but i don't understand the config options.
having 3 times as much sleep bar and while sleeping being able to get a full sleep bar in 8sec is what i really need. Any information would be appreciated.

**Comment by CallMeFoxie** [comment]
Hello, sorry for the delay, been packing my luggage for Minecon :)
you want to up giveSleepCounterOnSleep quite high to get a lot of sleep recovery JUST from laying on the bed.

**Comment by K4N0** [comment]
Thanks lots, I wish i could go, but i have to work. suxs. Lucky you, Hope you have fun!

**Comment by CallMeFoxie** [comment]
1.7.10 is no longer supported, if it is still relevant, please repost at https://github.com/CallMeFoxie/BetterSleeping2
