### ISSUE TITLE
Error displaying Sleepy Bar

### ISSUE THREAD

**Issue by dexman545** [OndraSter/BetterSleeping#28]
Using the mod recent version of Better Sleeping from Curseforge, and these mods (http://pastebin.com/WtU2iCNh), I can not seem to get the Sleepy Bar to display. Would it be possible for you to assist me in correcting this issue?

**Comment by CallMeFoxie** [comment]
Sure, will try to take a look later today after work :). Can I download the whole pack somewhere?

----- Původní zpráva -----
Od:"dexman545" notifications@github.com
Odesláno:‎17. ‎9. ‎2015 6:48
Komu:"CallMeFoxie/BetterSleeping" BetterSleeping@noreply.github.com
Předmět:[BetterSleeping] Error displaying Sleepy Bar (#28)

Using the mod recent version of Better Sleeping from Curseforge, and these mods (http://pastebin.com/WtU2iCNh), I can not seem to get the Sleepy Bar to display. Would it be possible for you to assist me in correcting this issue?

**Comment by dexman545** [comment]
Yes. The pack is avaiable on FTB launcher with code "Technofirma," and on CurseVoice. There is also a Git repository on my account (updated with most recent dev version, not released yet)

**Comment by CallMeFoxie** [comment]
Should have told me that it is Technofirma, I played it for a bit :)

Will take a look on Saturday when I get some free time :)

**Comment by dexman545** [comment]
Wow, what are the odds...

**Comment by CallMeFoxie** [comment]
Exactly as I expected, TFC removed XP bar and thus the rendering was not called ^^ will try to release it tonight as version 1.1 then.

**Comment by dexman545** [comment]
Thank you very much :)
