### ISSUE TITLE
[Suggestion] Spawn Setting

### ISSUE THREAD

**Issue by dexman545** [OndraSter/BetterSleeping#30]
In multiplayer settings, where it is advantageous to extend the period between sleeping for players, there arises the issue of setting one's spawn. If a player is not tired enough to sleep, they cannot set their spawn. Being able to set one's spawn without sleeping in the bed would be most useful, and allow for a better play experience.

**Comment by CallMeFoxie** [comment]
done for 1.10.2 branch
