### ISSUE TITLE
Modlister

### ISSUE THREAD

**Issue by K4N0** [OndraSter/BetterSleeping#33]
I am using modlister that links to a website to show what mods i am running on the Server.
It does not show your author name or link to your website.

http://modlister.com/server/Mojangsters

I'm unsure if it is something you have to add or if it's on their end.

**Comment by CallMeFoxie** [comment]
will look into it for the next release.

**Comment by K4N0** [comment]
thanks, just giving credit where it's due.

**Comment by CallMeFoxie** [comment]
Should be fixed in v1.2 http://minecraft.curseforge.com/projects/better-sleeping
