### ISSUE TITLE
Sleeping Once, Then Never Again

### ISSUE THREAD

**Issue by dexman545** [OndraSter/BetterSleeping#36]
Hello, on my server using this config: https://github.com/dexman545/technofirma/blob/master/config/bettersleeping.cfg some players sleep once in a bed, then they seem to be unable to get tired to sleep again. Other players are able to get tired after much sprint jumping (which is set to force players to get tired). Because players are unable to set there spawn since they can't sleep, this becomes an issue. Is something wrong in my config?

**Comment by CallMeFoxie** [comment]
1.7.10 is no longer supported, if it is still relevant, please repost at https://github.com/CallMeFoxie/BetterSleeping2
