### ISSUE TITLE
Sleep activation causing crash

### ISSUE THREAD

**Issue by LocalBoomer** [OndraSter/BetterSleeping#42]
I've had this on multiple worlds now where the 'collapsing' (or whatever it's actually called when the player get's really tired and collapses) mechanic causes my character to be in an 'incorrect ' position leading to my entire client crashing out then continuing to whenever I load up the affected worlds.

http://pastebin.com/KYagEMKL

http://pastebin.com/DxkrZR8h

http://pastebin.com/uFFVaqqf

http://pastebin.com/HrMw8H8w

(I'm pretty sure the only difference between each of these is the time-stamps but provided all just in case :P)

**Comment by CallMeFoxie** [comment]
ask
at com.ssblur.jwin.events.PlayerHandlers.sleepfix(PlayerHandlers.java:131)
author, it is not in my code.
