### ISSUE TITLE
problem of displaying with the tiredness bar

### ISSUE THREAD

**Issue by 0Navis0** [OndraSter/BetterSleeping#43]
I have noticed some problems of diplaying the tiredness bar I had already told on Minecraft CurseForge.
- The tiredness bar displays before the F3, chat and players list menu.
- The position of the bar change always depending of the size of Minecraft windows when the default option of top and left guioffset are changed.

**Comment by 0Navis0** [comment]
I add a new problem with the tiredness which continues to display while switching from survival to creative with the mod Just Enough Buttons.

**Comment by CallMeFoxie** [comment]
- no longer renders when F3 screen is open
- moved render to different time, might help with players list menu/chat

cannot simulate the position thing nor JEB thing. Works fine for me in both...

Also the project is at https://github.com/CallMeFoxie/BetterSleeping2

**Comment by 0Navis0** [comment]
Ok thanks, I will try to make a little video for showing you the problems. ;)

**Comment by 0Navis0** [comment]
[preview tiredness bar displaying problems.zip](https://github.com/CallMeFoxie/BetterSleeping/files/441230/preview.tiredness.bar.displaying.problems.zip)

**Comment by CallMeFoxie** [comment]
I see what's going on, I was not expecting somebody to move it and try to clip it to another corner :P 

Debating what would be the best decision as this is exactly how scaling should work, Unless I do some extra rendering and maths I can simply change the snap point to bottom right/... in the config.

**Comment by CallMeFoxie** [comment]
Orrrrrrr I could make it to % of the screen -- in that case it will never run out of the screen etc.

Or back to the previous idea of having snap points different than top left.

Which one would you think would be better?

**Comment by 0Navis0** [comment]
You should maybe look mod like Tought As Nails or Durability show which add menu and bars which display always to the same position even by changing the windows size. Maybe you will find how to do it in their code. ;)
I'm just a beginner in Minecraft modding, so I don't really know how displaying work in Minecraft, but if I can give a nice comparaison with HTML, you display your sleeping bar in absolute position while you should display it in relative position.

**Comment by CallMeFoxie** [comment]
It is relative. To the top left corner

**Comment by CallMeFoxie** [comment]
Using the Minecraft scaling thing...

**Comment by 0Navis0** [comment]
You should ask to the modders of Tough As Nails, Durability Show and Baubles Hud how they display their bars.
