### ISSUE TITLE
1.10.2 - Wake time calculations are off

### ISSUE THREAD

**Issue by joshiejack** [OndraSter/BetterSleeping#45]
If you go to sleep at 10:30am you wake up at 6:30am.
If you go to sleep at 11:13am you wake up at 6:13am.

You also wake up on the same minecraft day that you went to sleep.
So if you went to sleep at 10pm on day 11, you wake up at 6am on day 11.

**Comment by CallMeFoxie** [comment]
Should be fixed with https://github.com/CallMeFoxie/BetterSleeping2/commit/eb03d9dd4783d8dcbae330c7f84c5ac8c9251998
