### ISSUE TITLE
1.7.10 Server crash when a player wake up 

### ISSUE THREAD

**Issue by lightning02** [OndraSter/BetterSleeping#46]
http://pastebin.com/7xsZBqVq
Better sleeping v: 1.2.27
The player was sleeping on a terrafirmacraft straw bed, in the better sleeping config the setting is this:  http://pastebin.com/mJ5RyqQb

**Comment by CallMeFoxie** [comment]
Set both configs
chanceToGetBadNight
and
chanceToGetGoodNight
to 0

as TFC removes some potion effects. My best bet ;)

Any further actual fixes are not going to happen as 1.7.10 is long time closed and not supported, sorry. :(

**Comment by lightning02** [comment]
Yes, it seems to work! Thanks!! I don't know if it is a random case or not.

**Comment by CallMeFoxie** [comment]
it was a percentual chance ;P

**Comment by CallMeFoxie** [comment]
which is now set to 0% so it should be fine
