### ISSUE TITLE
Tired to death while right-clicking on bed

### ISSUE THREAD

**Issue by Sunsofold** [OndraSter/BetterSleeping#47]
Repeatedly received the 'not tired enough to sleep' message when clicking on the bed and then died.  
Kind of an important flaw there somewhere.

**Comment by CallMeFoxie** [comment]
Show me your config :)

**Comment by Sunsofold** [comment]
`# Configuration file

bedmodule {
    # Maximum day time to go to sleep at (-1 for anytime)
    I:maxTime=23999

    # Minimum day time to go to sleep at (-1 for anytime)
    I:minTime=0
}


debuffmodule {
    # Effect length of sleeping
    I:sleepInBedPotionLength=100

    # Potion IDs of random effects when sleeping
    S:sleepInBedPotions <
        resistance
        fire_resistance
        water_breathing
        absorbtion
        saturation
     >

    # Effect length of sleeping on the ground
    I:sleepOnGroundPotionLength=100

    # Potion IDs of random effects when sleeping on the ground
    S:sleepOnGroundPotions <
        moveSlowdown
        confusion
        weakness
     >
}


extra {
    B:allowSleepingInNether=false
}


gui {
    I:guiOffsetLeft=4
    I:guiOffsetTop=8
    B:renderBedIcon=true
}


randommodule {
    # Allow setting spawn just on using a bed
    B:alwaysSetSpawn=true

    # Chance to stop rain on world sleeping. 0 = never, 1 = always
    D:chanceToStopRain=0.7
}


tirednessmodule {
    # Disable overcharging energy
    B:capEnergy=true

    # Should player die when they reach zero energy? (if sleeping on the ground at == 0 then they will die first)
    B:dieOnExhaustion=true

    # Ticks before a player falls asleep
    I:dozingTimer=100

    # How much energy is lost per awake tick
    I:energyPerAwakeTick=1

    # Energy to spawn with
    I:energyToSpawnWith=48000

    # How much food is taken by every slept tick
    D:hungerPerSleptTick=1.0E-5

    # Maximum energy to allow sleeping at
    I:maximumEnergy=24000

    # Minimum energy to allow sleeping at
    I:minimumEnergy=4000

    # Do players get tired? (Disables everything related)
    B:playersGetTired=true

    # How much energy is regained per slept tick
    D:regainedEnergyPerSleptTick=3.0

    # At which energy the player falls asleep on the ground (-1 to disable)
    I:sleepOnGroundAt=200

    # Wake up time (24h day cycle, morning = 6h)
    I:wakeupHour=6

    # Wake up with sleeping cap
    B:wakeupOnCap=false
}`

AND

`# Configuration file

debuffs {
    # Enable this debuff [default: true]
    B:blindness_enable=true

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:blindness_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 2]
    I:blindness_maxScale=2

    # Enable this debuff [default: false]
    B:hunger_enable=false

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:hunger_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 1]
    I:hunger_maxScale=1

    # Enable this debuff [default: true]
    B:mining_fatigue_enable=true

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:mining_fatigue_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 3]
    I:mining_fatigue_maxScale=3

    # Enable this debuff [default: false]
    B:nausea_enable=false

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:nausea_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 1]
    I:nausea_maxScale=1

    # Enable this debuff [default: false]
    B:poison_enable=false

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:poison_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 1]
    I:poison_maxScale=1

    # Enable this debuff [default: true]
    B:slowness_enable=true

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:slowness_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 3]
    I:slowness_maxScale=3

    # Enable this debuff [default: true]
    B:weakness_enable=true

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:weakness_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 3]
    I:weakness_maxScale=3

    # Enable this debuff [default: false]
    B:wither_enable=false

    # At which level is this debuff applied [range: 1 ~ 23999, default: 800]
    I:wither_level=800

    # Maximum scaling of this debuff [range: 0 ~ 5, default: 1]
    I:wither_maxScale=1
}


`

**Comment by CallMeFoxie** [comment]
Grabbed the config and it runs fine here? Are you on the latest version for MC1.10.2?

**Comment by Sunsofold** [comment]
Well, that's new.  I opened curse to make sure I was using the latest version and it wasn't on the list of installed mods.  I installed it again and tested by playing through a day.
Early in the night, I was tired enough to get status effects.  I attempted to rest and got the same 'not tired enough' response.  I passed out on the floor.  When I woke up, the statuses cleared and then almost immediately restarted.  I passed out on the floor again.  I woke up and passed out a third time, still trying to use the bed and getting a 'your spawn has been set' response, the 'not tired enough' line was no longer showing.  
And as a last confusion inducing moment, I played a bit longer to see if I could get a more consistent result or see a pattern, and when I tried to sleep the next night, it gave me 'your spawn has been set' (no 'you are not tired' line) for the first click, and let me sleep in the bed on the second click.  
I'm going to try going for another day and see if I can spot some kind of pattern.

(the above were the default configs.  I hadn't looked into modifying them yet.)

**Comment by Sunsofold** [comment]
Well, whatever you changed today seems to have kind of fixed the problem.  There is at least consistency now and it's good consistency.
The strangeness is that there seems to be a kind of sleeping range, inside of which, you sleep, outside of which you just set your spawn.  You have to be standing up against the bed to sleep.

**Comment by CallMeFoxie** [comment]
Note that there may be other mods involved who mess up the sleeping schedule! I only override vanilla checks but still respect other mods' opinions about sleeping ;)


The issue with sleeping on the ground and waking up immediatily sounds like a coremod not being loaded... which it should.

And I changed nothing today. Last release was many days ago ;P

**Comment by Sunsofold** [comment]
That's odd.  Curse showed it as last updated March 25th.  Maybe it's something wrong with Curse.
Well, thanks for the help all the same.  I love the mod now that it seems to be working.  The only other mod I have that modifies sleeping is the sleeping bag mod by shadowfactsmc and it works perfectly well with yours.
