### ISSUE TITLE
Compatbility with Somnia

### ISSUE THREAD

**Issue by labpaw** [OndraSter/BetterSleeping#9]
Found small interaction bug with Somnia(https://github.com/kingrunes/Somnia). It can be easily reproduced in creative mode, not tested in survival. Steps to reproduce: 
1) Install both Better Sleeping and Somnia.
2) Create new world in creative.
3) Wait till you tired and fall asleep.
4) Better Sleeping will say that player is tired but Somnia will say no.
5) Congratulations. You stuck. You can't leave the bed(ground) and can't sleep.
Few screenshots: http://i.imgur.com/Ec6Yq5Z.jpg http://i.imgur.com/SflKaub.jpg

**Comment by CallMeFoxie** [comment]
Thanks for the report, will look into it.
Not sure what I will be able to do as there is no API inside.

**Comment by CallMeFoxie** [comment]
Actually looking into his code he totally reimplemented the vanilla sleeping code over here https://github.com/kingrunes/Somnia/blob/master/src/com/kingrunes/somnia/common/CommonProxy.java#L197
Can not fix this in any easy and nice way, sorry.

**Comment by labpaw** [comment]
Maybe it can be fixed on Somnia side? What do you think?

**Comment by CallMeFoxie** [comment]
I am providing some API right now, if he needs more I can add it :) (Read: he has got much better chance of fixing it from his side than me from my side)
